server:
  port: 8181
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
  redis:
    lettuce:
      pool:
        max-active: 10
        max-wait: 6000ms
        min-idle: 5
        max-idle: 8
    host: 192.168.43.216
    database: 1